language: rust
rust:
  - beta
  - nightly
cache: cargo
env:
- MCU=stm32l100
- MCU=stm32l151
- MCU=stm32l152
- MCU=stm32l162
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - rustup target add thumbv7m-none-eabi
  - cargo build --features=$MCU
  - cargo build --features=$MCU,rt
  - cargo build --features=$MCU,rt --examples
